// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8z7qGJ4WYcVN8eZspczOvbRbuNJKx7eY',
    appId: '1:757457922216:web:b76c922f89c8da0850ba9d',
    messagingSenderId: '757457922216',
    projectId: 'vsms-app-3eb24',
    authDomain: 'vsms-app-3eb24.firebaseapp.com',
    storageBucket: 'vsms-app-3eb24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp9184iwOvx09-Uz6T0ZShBYqcZf0TOUo',
    appId: '1:757457922216:android:fb417b2bdc4a659450ba9d',
    messagingSenderId: '757457922216',
    projectId: 'vsms-app-3eb24',
    storageBucket: 'vsms-app-3eb24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCev7BJNwKEOEIR4iQvA7MQ_VoMpdxqXZE',
    appId: '1:757457922216:ios:a1c8f9b488fcff7050ba9d',
    messagingSenderId: '757457922216',
    projectId: 'vsms-app-3eb24',
    storageBucket: 'vsms-app-3eb24.firebasestorage.app',
    iosBundleId: 'com.example.visitorManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8z7qGJ4WYcVN8eZspczOvbRbuNJKx7eY',
    appId: '1:757457922216:web:9e797fe00919621550ba9d',
    messagingSenderId: '757457922216',
    projectId: 'vsms-app-3eb24',
    authDomain: 'vsms-app-3eb24.firebaseapp.com',
    storageBucket: 'vsms-app-3eb24.firebasestorage.app',
  );
}
